[package]
name = "day_5"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-hal = "1.0.0"

[[bin]]
name = "ex1_traits"
path = "ex1_traits/main.rs"

[[bin]]
name = "ex2_traits"
path = "ex2_traits/main.rs"
